<?php

namespace AppBundle\Repository;

/**
 * ChallengeBatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeBatchRepository extends \Doctrine\ORM\EntityRepository
{
}
