<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends EntityRepository
{   
    /**
     * Filter by game.id
     */
    public function findAllQueryBuilder($filter = '') {
        $qb = $this->createQueryBuilder('challenge');
        if($filter) {
            $qb->andWhere('challenge.game = :filter')
                ->setParameter('filter', $filter);
        }
        return $qb;
    }


}
