<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findAllQueryBuilder($filter = '') {
        $qb = $this->createQueryBuilder('event');

        if($filter) {
            $qb->andWhere('event.game = :filter')
                ->setParameter('filter', $filter);
        }

        return $qb->orderBy('event.date', 'DESC');
    }
}
