<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findAllQueryBuilder($filter = '') {
        return $this->createQueryBuilder('event')
                    ->orderBy('event.date', 'DESC');
    }
}
